"""Deterministic, wholly generated human projection. Historical text stays inert."""

from string import punctuation
from model import INDEX


def code(value):
    """Keep literal text inert through staging, mdBook helpers, Markdown, and HTML.

    Raw <code> tags do not shield their contents from the earlier parsers. Encode
    ASCII syntax and line separators in one pass; entities decode only as text,
    never as another round of Markdown/helpers (including literal input entities).
    """
    literal = "".join(f"&#{ord(char)};" if char in punctuation + "\n\r\t" else char
                      for char in str(value))
    return "<code>" + literal + "</code>"


def link(path):
    destination = path.removeprefix("docs/") if path.startswith("docs/") else "../" + path
    return f"[{path}]({destination})"


def render(index, observed):
    lines = [
        "# Authority claims and supersession", "",
        "<!-- Generated by scripts/authority_claims/check.py --write. Do not edit. -->", "",
        f"This is the sole aggregate projection of {link(INDEX)}, a cross-domain index,",
        "not replacement policy. Existing source owners and precedence remain authoritative.", "",
        f"Fast checker: {link('scripts/authority_claims/check.py')}.", "",
        "## Verification modes and limits", "",
        "- **Delegated:** display structured owner data and bind its exact bytes. The fast checker",
        "  does not run Cargo/package closure, public row classification, or catalog provenance/registry",
        "  validators. Those existing owners run separately in CI and the full gate.",
        "- **Native:** expected observations below are compared with compiled private constants or",
        "  `oce_blocks::catalog()` by test-only owner modules. Python never extracts Rust literals.",
        "  A fast-check PASS alone does **not** mean native comparisons passed.",
        "- **Corpus:** count raw provenance records and check universal tier/dependency metadata.",
        "  These are fixture inventory facts, **not correctness or independence proofs**.",
        "- **Review-only:** links and limits are explicit; semantics and support promises are not automated.",
        "  No arbitrary Markdown, historical archive, or Rust semantics parser is involved.", "",
        "## Checked source bindings", "",
        "| Fact | Mode | True source | Owner verifier |", "| --- | --- | --- | --- |",
    ]
    facts = sorted(index["facts"], key=lambda row: row["id"])
    for row in facts:
        if row["mode"] != "review-only":
            # Corpus directories are links to fixed declared roots, not user-selected paths.
            lines.append(f"| {row['id']} | {row['mode']} | {link(row['source'])} | {link(row['verifier'])} |")
    packages = observed["packages"]["value"]
    publishable = sum(row["publish"] for row in packages["packages"])
    lines += ["", "## Delegated owner observations", "",
              f"Packages: **{len(packages['packages'])} members; {publishable} publishable; "
              f"{len(packages['packages']) - publishable} private**. Publication state: {code(packages['publication_state'])}.",
              f"Feature selections: **{len(packages['feature_contract']['selections'])}**; the shared normal closure is owner-verified, not inferred here.", "",
              "| Package | Classification | Publishable |", "| --- | --- | --- |"]
    for row in sorted(packages["packages"], key=lambda r: r["name"]):
        lines.append(f"| {code(row['name'])} | {code(row['category'])} | {str(row['publish']).lower()} |")
    public = observed["public-surface"]["value"]
    lines += ["", "| Public baseline | Descriptor rows | SHA-256 (owner descriptor) |", "| --- | --- | --- |"]
    for row in sorted(public["baselines"], key=lambda r: r["id"]):
        lines.append(f"| {link(row['path'])} | {row['item_count']} | {code(row['sha256'])} |")
    lines += ["", "Exact row assignments remain in the public ledger; statuses below are displayed, not re-adjudicated.", "",
              "| Group | Status |", "| --- | --- |"]
    for name, row in sorted(public["groups"].items()):
        lines.append(f"| {code(name)} | {code(row['status'])} |")
    source = observed["catalog-source"]["value"]
    lines += ["", f"CDL source revision: {code(source['commit'])}; catalog fingerprint: {code(source['catalog_fingerprint'])}.",
              "This is the existing pinned source identity, not a new numeric catalog revision.", "",
              "| Delegated source | SHA-256 (exact input bytes) |", "| --- | --- |"]
    for row in facts:
        if row["mode"] == "delegated":
            lines.append(f"| {row['id']} | {code(observed[row['id']]['sha256'])} |")
    lines += ["", "## Native expected observations", "", "| Fact | Expected |", "| --- | --- |"]
    for row in facts:
        if row["mode"] == "native":
            lines.append(f"| {row['id']} | {row['expected']} |")
    lines += ["", "## Raw evidence inventories", "",
              "Each declared root is enumerated recursively and completely, sorted by repository-relative",
              "path. Only tracked regular `.csv`, `*.prov.json`, and the fixed Tier-A `MANIFEST.txt` are admitted; missing, unexpected,",
              "untracked, ignored, or symlink members fail. All JSON records must be objects with the stated",
              "`tier` and Boolean `depends_on_oce_blocks`. Other record fields and CSV contents are opaque,",
              "not semantically validated. The inventory SHA-256 hashes sorted lines of",
              "`<file-sha256>  <repository-relative-path>\\n`, including **every** member, not just records.",
              "Thus added/removed/renamed or byte-changed evidence cannot leave the projection unchanged.", "",
              "| Corpus | Provenance records | All members | Tier | depends_on_oce_blocks | Inventory SHA-256 |",
              "| --- | --- | --- | --- | --- | --- |"]
    for row in facts:
        if row["mode"] == "corpus":
            value = observed[row["id"]]
            lines.append(f"| {row['id']} | {value['records']} | {value['members']} | {value['tier']} | {str(value['depends_on_oce_blocks']).lower()} | {code(value['inventory_sha256'])} |")
    lines += ["", "## Review-only claims", "", "| Family | Existing evidence | Limit |", "| --- | --- | --- |"]
    for row in facts:
        if row["mode"] == "review-only":
            lines.append(f"| {row['id']} | {link(row['source'])}; {link(row['verifier'])} | {code(row['limit'])} |")
    lines += ["", "## Representative supersession map — non-exhaustive", "",
              "This is **not a global history audit**. Historical locators are inert text: never opened,",
              "linked, or checked for existence. No archive, `_spec/`, or `_research/` is a prerequisite.",
              "Formatting cannot promote a lower-precedence record to authority. A null authority records",
              "an unresolved question, not permission to select a new owner.", "",
              "| ID / subject | Historical locator (text only) | Status | Current authority | Superseded by | Reason / responsibility owner |",
              "| --- | --- | --- | --- | --- | --- |"]
    for row in sorted(index["supersession"], key=lambda r: r["id"]):
        authority = link(row["authority_path"]) if row["authority_path"] else "Unresolved"
        lines.append(f"| {row['id']} / {code(row['subject'])} | {code(row['historical_locator'])} | {row['status']} | {authority} | {code(row.get('superseded_by', '—'))} | {code(row['reason'])} / {code(row['responsibility_owner'])} |")
    lines += ["", "## Updating a legitimate claim", "",
              "1. Edit the **true owner first**, following its existing compatibility/review policy.",
              "2. If a compiled numeric fact legitimately changes, update its native `expected` observation",
              "   in the index. Never copy delegated counts, classifications, or matrices into the index.",
              "3. Explicitly regenerate only this page with `python3 scripts/authority_claims/check.py --write`.",
              "4. Run the named owner verifier(s), `python3 scripts/authority_claims/check.py --check`,",
              "   and the repository gate described in [CI and the gate](ci-and-the-gate.md).",
              "   Gate execution never regenerates or blesses this artifact.", "",
              "The tool uses Python 3 and Git, standard library only, no network. Local development admits",
              "only declared pending nonignored checker/index/projection files; corpus and existing owner",
              "inputs must be tracked. A clean exact-commit checkout verifies final clone availability.",
              "Schema, fixed source/verifier bindings, and explicit historical status mappings are closed;",
              "expanding them is a reviewed protocol change, not automatic discovery of new authority.", ""]
    return "\n".join(lines).encode("utf-8")
