//! Independently authored serialization twins shared with the public identity tests.
//! These are OCE profile examples, not output from Studio, OCL or a Modelica oracle.

use serde_json::Value;

pub const COMPACT: &str = r#"{
  "@context": {"m":"urn:order:", "cdl":"http://example.org#Buildings.Controls.OBC.CDL.", "S231":"http://data.ashrae.org/S231P#"},
  "@graph": [
    {"@id":"m:M", "@type":"S231:Block",
     "S231:containsBlock":[{"@id":"m:M.branch"},{"@id":"m:M.off"},{"@id":"m:M.tail"}],
     "S231:hasParameter":[{"@id":"m:M.gain"},{"@id":"m:M.base"}],
     "S231:hasConstant":[{"@id":"m:M.shift"},{"@id":"m:M.unused"}],
     "S231:hasOutput":[{"@id":"m:M.outSum"},{"@id":"m:M.outTail"}]},
    {"@id":"m:M.branch", "@type":"S231:Block", "S231:containsBlock":[{"@id":"m:M.branch.zSource"},{"@id":"m:M.branch.aSum"}]},
    {"@id":"m:M.tail", "@type":"cdl:Reals.Add", "S231:hasInput":[{"@id":"m:M.tail.u2"},{"@id":"m:M.tail.u1"}], "S231:hasOutput":{"@id":"m:M.tail.y"}},
    {"@id":"m:M.branch.aSum", "@type":"cdl:Reals.Add", "S231:hasInput":[{"@id":"m:M.branch.aSum.u2"},{"@id":"m:M.branch.aSum.u1"}], "S231:hasOutput":{"@id":"m:M.branch.aSum.y"}},
    {"@id":"m:M.branch.zSource", "@type":"cdl:Reals.Sources.Constant", "S231:hasOutput":{"@id":"m:M.branch.zSource.y"}, "S231:hasParameter":{"@id":"m:M.branch.zSource.k"}},
    {"@id":"m:M.branch.aSum.u2", "@type":"S231:RealInput"},
    {"@id":"m:M.tail.y", "@type":"S231:RealOutput", "S231:isConnectedTo":{"@id":"m:M.outTail"}},
    {"@id":"m:M.branch.zSource.y", "@type":"S231:RealOutput", "S231:isConnectedTo":[{"@id":"m:M.tail.u2"},{"@id":"m:M.branch.aSum.u1"},{"@id":"m:M.tail.u1"},{"@id":"m:M.branch.aSum.u2"}]},
    {"@id":"m:M.tail.u1", "@type":"S231:RealInput"},
    {"@id":"m:M.branch.aSum.y", "@type":"S231:RealOutput", "S231:isConnectedTo":{"@id":"m:M.outSum"}},
    {"@id":"m:M.branch.aSum.u1", "@type":"S231:RealInput"},
    {"@id":"m:M.tail.u2", "@type":"S231:RealInput"},
    {"@id":"m:M.outTail", "@type":"S231:RealOutput"},
    {"@id":"m:M.outSum", "@type":"S231:RealOutput"},
    {"@id":"m:M.gain", "S231:value":"base + shift"},
    {"@id":"m:M.base", "S231:value":1.0},
    {"@id":"m:M.shift", "S231:value":1.0},
    {"@id":"m:M.unused", "S231:value":false},
    {"@id":"m:M.branch.zSource.k", "S231:value":"gain"},
    {"@id":"m:M.off", "@type":"S231:Block", "S231:isConditionalComponent":true, "S231:conditionalExpression":"unused", "S231:containsBlock":[{"@id":"m:M.off.bad"}]},
    {"@id":"m:M.off.bad", "@type":"cdl:NotRegistered", "S231:isReplaceable":true}
  ]
}"#;

// Written separately, not generated by the importer, exporter, or a token replacement helper.
// Context-map order, object-key order, singleton arrays, type arrays and identity spellings differ.
pub const EXPANDED: &str = r#"{
  "@graph": [
    {"S231:hasOutput":[{"@id":"urn:order:M.outSum"},{"@id":"urn:order:M.outTail"}],
     "S231:hasConstant":[{"@id":"urn:order:M.shift"},{"@id":"urn:order:M.unused"}],
     "S231:hasParameter":[{"@id":"urn:order:M.gain"},{"@id":"urn:order:M.base"}],
     "S231:containsBlock":[{"@id":"urn:order:M.branch"},{"@id":"urn:order:M.off"},{"@id":"urn:order:M.tail"}],
     "@type":["http://data.ashrae.org/S231P#Block"], "@id":"urn:order:M"},
    {"S231:containsBlock":[{"@id":"urn:order:M.branch.zSource"},{"@id":"urn:order:M.branch.aSum"}], "@type":"http://data.ashrae.org/S231P#Block", "@id":"urn:order:M.branch"},
    {"S231:hasOutput":[{"@id":"urn:order:M.tail.y"}], "S231:hasInput":[{"@id":"urn:order:M.tail.u2"},{"@id":"urn:order:M.tail.u1"}], "@type":"http://example.org#Buildings.Controls.OBC.CDL.Reals.Add", "@id":"urn:order:M.tail"},
    {"S231:hasOutput":[{"@id":"urn:order:M.branch.aSum.y"}], "S231:hasInput":[{"@id":"urn:order:M.branch.aSum.u2"},{"@id":"urn:order:M.branch.aSum.u1"}], "@type":"http://example.org#Buildings.Controls.OBC.CDL.Reals.Add", "@id":"urn:order:M.branch.aSum"},
    {"S231:hasParameter":[{"@id":"urn:order:M.branch.zSource.k"}], "S231:hasOutput":[{"@id":"urn:order:M.branch.zSource.y"}], "@type":"http://example.org#Buildings.Controls.OBC.CDL.Reals.Sources.Constant", "@id":"urn:order:M.branch.zSource"},
    {"@type":"http://data.ashrae.org/S231P#RealInput", "@id":"urn:order:M.branch.aSum.u2"},
    {"S231:isConnectedTo":[{"@id":"urn:order:M.outTail"}], "@type":"http://data.ashrae.org/S231P#RealOutput", "@id":"urn:order:M.tail.y"},
    {"S231:isConnectedTo":[{"@id":"urn:order:M.tail.u2"},{"@id":"urn:order:M.branch.aSum.u1"},{"@id":"urn:order:M.tail.u1"},{"@id":"urn:order:M.branch.aSum.u2"}], "@type":"http://data.ashrae.org/S231P#RealOutput", "@id":"urn:order:M.branch.zSource.y"},
    {"@type":"http://data.ashrae.org/S231P#RealInput", "@id":"urn:order:M.tail.u1"},
    {"S231:isConnectedTo":[{"@id":"urn:order:M.outSum"}], "@type":"http://data.ashrae.org/S231P#RealOutput", "@id":"urn:order:M.branch.aSum.y"},
    {"@type":"http://data.ashrae.org/S231P#RealInput", "@id":"urn:order:M.branch.aSum.u1"},
    {"@type":"http://data.ashrae.org/S231P#RealInput", "@id":"urn:order:M.tail.u2"},
    {"@type":"http://data.ashrae.org/S231P#RealOutput", "@id":"urn:order:M.outTail"},
    {"@type":"http://data.ashrae.org/S231P#RealOutput", "@id":"urn:order:M.outSum"},
    {"S231:value":"base + shift", "@id":"urn:order:M.gain"},
    {"S231:value":1.0, "@id":"urn:order:M.base"},
    {"S231:value":1.0, "@id":"urn:order:M.shift"},
    {"S231:value":false, "@id":"urn:order:M.unused"},
    {"S231:value":"gain", "@id":"urn:order:M.branch.zSource.k"},
    {"S231:containsBlock":[{"@id":"urn:order:M.off.bad"}], "S231:conditionalExpression":"unused", "S231:isConditionalComponent":true, "@type":"http://data.ashrae.org/S231P#Block", "@id":"urn:order:M.off"},
    {"S231:isReplaceable":true, "@type":"http://example.org#Buildings.Controls.OBC.CDL.NotRegistered", "@id":"urn:order:M.off.bad"}
  ],
  "@context": [{"S231":"http://data.ashrae.org/S231P#"}, {"m":"urn:order:"}]
}"#;

pub fn node_mut<'a>(doc: &'a mut Value, id: &str) -> &'a mut Value {
    doc["@graph"]
        .as_array_mut()
        .unwrap()
        .iter_mut()
        .find(|node| node["@id"] == id)
        .unwrap()
}

/// Deliberately bypass serde_json's map iteration order while leaving every array untouched.
pub fn reverse_object_keys(value: &Value) -> String {
    match value {
        Value::Object(map) => format!(
            "{{{}}}",
            map.iter()
                .rev()
                .map(|(key, value)| format!(
                    "{}:{}",
                    serde_json::to_string(key).unwrap(),
                    reverse_object_keys(value)
                ))
                .collect::<Vec<_>>()
                .join(",")
        ),
        Value::Array(array) => format!(
            "[{}]",
            array
                .iter()
                .map(reverse_object_keys)
                .collect::<Vec<_>>()
                .join(",")
        ),
        _ => serde_json::to_string(value).unwrap(),
    }
}
