//! Export content oracle over the 47-document swept CXF corpus: 46 G36 catalog fixtures and one
//! resolver contract.
//!
//! For every fixture this pins two things against a checked-in expectation file:
//! the FNV-1a-128 digest of [`oce_api::ExportReport::bytes`], and the completeness state of
//! [`oce_api::ExportReport::content_id_complete`] — `ok` when a complete content identity is
//! mintable, `incomplete:<n>` when `n` deferral warnings withhold one. The digest is computed
//! here by an independent FNV-1a-128 implementation (the algorithm is documented on
//! `content_id_complete`), so the byte pin does not answer to the method under test; on the
//! `ok` arm the minted id is additionally cross-checked against that independent digest.
//! Incomplete fixtures are pinned at the same strength as complete ones — by byte digest, not
//! by warning count alone.
//!
//! HONESTY SEQUENCE (load-bearing commit order): the expectation file was first generated by
//! this test's `OCE_BLESS` arm at `development`@`c06a657`, before any `@context`-expansion
//! code existed. It was regenerated under the #233 ruling when declared boundary outputs began
//! exporting their authored attributes, then under #273 when §7.10 propagation began joining those
//! attributes to their source connectors, then under #243 when surviving boundary inputs began
//! exporting their declaration-local attributes. The checked-in file is therefore a post-#243
//! current-engine snapshot. Direct validator tests pin output propagation and conflict rules;
//! `export_declared_input_attrs.rs` independently proves that removing only #243's five scoped keys
//! recovers every pre-#243 export. Regenerating the file (`OCE_BLESS=1`) replaces its evidence with
//! another current-engine snapshot, so do so only for a ratified behavior change and record why.

use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;

use oce_api::{ContentIdError, Engine};

/// Header of the generated expectation file. Names the owning test so the file never sits
/// orphaned in the `oce-cxf` fixtures tree, and restates the honesty sequence so a reader of
/// the file alone knows what its digests are evidence of.
const FILE_HEADER: &str = "\
# Swept CXF export content oracle expectations.
# Owner test: crates/oce-api/tests/export_content_oracle.rs (regenerate with OCE_BLESS=1).
# Honesty sequence: first generated at development@c06a657, before @context expansion;
# regenerated under #233 for authored declared-output attrs, then under #273 when section-7.10
# propagation joined those attrs to their source connectors, then under #243 for declaration-local
# boundary-input attrs. This is a post-#243 current-engine snapshot; export_declared_input_attrs.rs
# proves that stripping only #243's five scoped keys recovers every pre-#243 corpus export.
# Format: <fixture stem> <fnv1a128 hex over ExportReport::bytes> ok|incomplete:<warnings>
";

/// The checked-in expectation file, beside the corpus it describes (the same relative route
/// `authored_point_identity.rs` uses to reach the G36 tree).
fn expectation_path() -> PathBuf {
    PathBuf::from(format!(
        "{}/../oce-cxf/tests/fixtures/expectations/g36_export_content.txt",
        env!("CARGO_MANIFEST_DIR")
    ))
}

/// Every `.jsonld` document in the swept CXF corpus, sorted for deterministic iteration order.
fn corpus_fixtures() -> Vec<PathBuf> {
    let fixture_dir = format!(
        "{}/../oce-cxf/tests/fixtures/g36",
        env!("CARGO_MANIFEST_DIR")
    );
    let mut fixtures = fs::read_dir(fixture_dir)
        .expect("read swept CXF fixture corpus")
        .map(|entry| entry.expect("fixture directory entry").path())
        .filter(|path| {
            path.extension()
                .is_some_and(|extension| extension == "jsonld")
        })
        .collect::<Vec<_>>();
    fixtures.sort();
    assert_eq!(fixtures.len(), 47, "swept CXF corpus size moved");
    fixtures
}

/// FNV-1a-128 over `bytes` as 32 lowercase hex characters — the algorithm
/// `content_id_complete` documents, implemented independently of it.
fn fnv1a128_hex(bytes: &[u8]) -> String {
    const OFFSET: u128 = 0x6c62_272e_07bb_0142_62b8_2175_6295_c58d;
    const PRIME: u128 = 0x0000_0000_0100_0000_0000_0000_0000_013b;
    let mut hash = OFFSET;
    for byte in bytes {
        hash ^= u128::from(*byte);
        hash = hash.wrapping_mul(PRIME);
    }
    format!("{hash:032x}")
}

/// Render the whole expectation file from the current engine: header plus one
/// `<stem> <digest> <state>` line per fixture in sorted order.
fn rendered_expectations() -> String {
    let mut rendered = String::from(FILE_HEADER);
    for fixture in corpus_fixtures() {
        let stem = fixture
            .file_stem()
            .and_then(|stem| stem.to_str())
            .expect("UTF-8 fixture stem")
            .to_owned();
        let bytes = fs::read(&fixture).expect("read swept CXF fixture");
        let mut engine = Engine::in_memory();
        engine
            .load_cxf(&bytes)
            .unwrap_or_else(|error| panic!("{stem} loads: {error:?}"));
        let export = engine
            .export_cxf()
            .unwrap_or_else(|error| panic!("{stem} exports: {error:?}"));
        let digest = fnv1a128_hex(&export.bytes);
        let state = match export.content_id_complete() {
            Ok(id) => {
                assert_eq!(
                    id,
                    format!("cxf:fnv1a128:{digest}"),
                    "{stem}: minted content id diverges from the independent digest of bytes"
                );
                "ok".to_owned()
            }
            Err(ContentIdError::Incomplete { warning_count, .. }) => {
                format!("incomplete:{warning_count}")
            }
            Err(other) => panic!("{stem}: unexpected content-id error {other:?}"),
        };
        writeln!(rendered, "{stem} {digest} {state}").expect("write expectation line");
    }
    rendered
}

#[test]
fn every_g36_export_matches_the_recorded_content_expectation() {
    let rendered = rendered_expectations();
    let path = expectation_path();
    if oce_bless::enabled("OCE_BLESS") {
        fs::write(&path, &rendered).expect("write export content expectation file");
        return;
    }
    let checked_in = fs::read_to_string(&path)
        .expect("read export content expectation file")
        .replace("\r\n", "\n");
    assert_eq!(
        checked_in, rendered,
        "exported bytes or completeness state moved against the recorded expectation"
    );
}
