//! Corpus-wide CXF export content oracle over the 46 G36 fixtures.
//!
//! For every fixture this pins two things against a checked-in expectation file:
//! the FNV-1a-128 digest of [`oce_api::ExportReport::bytes`], and the completeness state of
//! [`oce_api::ExportReport::content_id_complete`] — `ok` when a complete content identity is
//! mintable, `incomplete:<n>` when `n` deferral warnings withhold one. The digest is computed
//! here by an independent FNV-1a-128 implementation (the algorithm is documented on
//! `content_id_complete`), so the byte pin does not answer to the method under test; on the
//! `ok` arm the minted id is additionally cross-checked against that independent digest.
//! Incomplete fixtures are pinned at the same strength as complete ones — by byte digest, not
//! by warning count alone.
//!
//! HONESTY SEQUENCE (load-bearing commit order): the expectation file was first generated by
//! this test's `OCE_BLESS` arm at `development`@`c06a657`, BEFORE any `@context`-expansion
//! code existed, and regenerated ONCE under the #233 owner ruling (2026-08-05), which
//! intentionally moved the exported bytes of the 29 fixtures carrying at least one
//! attr-carrying surviving declared boundary output. The digests are therefore two kinds of
//! evidence: base-engine rows for the 17 fixtures that regeneration left byte-identical, and
//! post-#233 current-engine rows for the 29 that moved. Either way the file was recorded
//! BEFORE any later change, which is what makes it an oracle rather than a snapshot: a change
//! that moves any exported byte or any completeness state fails here against recorded
//! evidence. Regenerating the file (`OCE_BLESS=1`) replaces that evidence with a snapshot of
//! the current engine — do so only for a ratified behavior change, and say so in the commit.

use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;

use oce_api::{ContentIdError, Engine};

/// Header of the generated expectation file. Names the owning test so the file never sits
/// orphaned in the `oce-cxf` fixtures tree, and restates the honesty sequence so a reader of
/// the file alone knows what its digests are evidence of.
const FILE_HEADER: &str = "\
# G36 export content oracle expectations.
# Owner test: crates/oce-api/tests/export_content_oracle.rs (regenerate with OCE_BLESS=1).
# Honesty sequence: first generated at development@c06a657, BEFORE the @context-expansion
# implementation existed; regenerated once under the #233 owner ruling (2026-08-05), when
# declared boundary outputs began exporting their authored section-7.4.1 attrs. The 29 rows
# that ruling moved are post-#233 current-engine evidence; the other 17 rows are still the
# base-engine digests. A later OCE_BLESS regeneration replaces this evidence with a
# current-engine snapshot.
# Format: <fixture stem> <fnv1a128 hex over ExportReport::bytes> ok|incomplete:<warnings>
";

/// The checked-in expectation file, beside the corpus it describes (the same relative route
/// `authored_point_identity.rs` uses to reach the G36 tree).
fn expectation_path() -> PathBuf {
    PathBuf::from(format!(
        "{}/../oce-cxf/tests/fixtures/expectations/g36_export_content.txt",
        env!("CARGO_MANIFEST_DIR")
    ))
}

/// Every `.jsonld` document in the G36 corpus, sorted for deterministic iteration order.
fn corpus_fixtures() -> Vec<PathBuf> {
    let fixture_dir = format!(
        "{}/../oce-cxf/tests/fixtures/g36",
        env!("CARGO_MANIFEST_DIR")
    );
    let mut fixtures = fs::read_dir(fixture_dir)
        .expect("read G36 fixture corpus")
        .map(|entry| entry.expect("fixture directory entry").path())
        .filter(|path| {
            path.extension()
                .is_some_and(|extension| extension == "jsonld")
        })
        .collect::<Vec<_>>();
    fixtures.sort();
    assert_eq!(fixtures.len(), 46, "G36 corpus size moved");
    fixtures
}

/// FNV-1a-128 over `bytes` as 32 lowercase hex characters — the algorithm
/// `content_id_complete` documents, implemented independently of it.
fn fnv1a128_hex(bytes: &[u8]) -> String {
    const OFFSET: u128 = 0x6c62_272e_07bb_0142_62b8_2175_6295_c58d;
    const PRIME: u128 = 0x0000_0000_0100_0000_0000_0000_0000_013b;
    let mut hash = OFFSET;
    for byte in bytes {
        hash ^= u128::from(*byte);
        hash = hash.wrapping_mul(PRIME);
    }
    format!("{hash:032x}")
}

/// Render the whole expectation file from the current engine: header plus one
/// `<stem> <digest> <state>` line per fixture in sorted order.
fn rendered_expectations() -> String {
    let mut rendered = String::from(FILE_HEADER);
    for fixture in corpus_fixtures() {
        let stem = fixture
            .file_stem()
            .and_then(|stem| stem.to_str())
            .expect("UTF-8 fixture stem")
            .to_owned();
        let bytes = fs::read(&fixture).expect("read G36 fixture");
        let mut engine = Engine::in_memory();
        engine
            .load_cxf(&bytes)
            .unwrap_or_else(|error| panic!("{stem} loads: {error:?}"));
        let export = engine
            .export_cxf()
            .unwrap_or_else(|error| panic!("{stem} exports: {error:?}"));
        let digest = fnv1a128_hex(&export.bytes);
        let state = match export.content_id_complete() {
            Ok(id) => {
                assert_eq!(
                    id,
                    format!("cxf:fnv1a128:{digest}"),
                    "{stem}: minted content id diverges from the independent digest of bytes"
                );
                "ok".to_owned()
            }
            Err(ContentIdError::Incomplete { warning_count, .. }) => {
                format!("incomplete:{warning_count}")
            }
            Err(other) => panic!("{stem}: unexpected content-id error {other:?}"),
        };
        writeln!(rendered, "{stem} {digest} {state}").expect("write expectation line");
    }
    rendered
}

#[test]
fn every_g36_export_matches_the_recorded_content_expectation() {
    let rendered = rendered_expectations();
    let path = expectation_path();
    if oce_bless::enabled("OCE_BLESS") {
        fs::write(&path, &rendered).expect("write export content expectation file");
        return;
    }
    let checked_in = fs::read_to_string(&path)
        .expect("read export content expectation file")
        .replace("\r\n", "\n");
    assert_eq!(
        checked_in, rendered,
        "exported bytes or completeness state moved against the recorded expectation"
    );
}
