//! In-crate facade tests grouped by scenario.

mod boundary_alias_tests;
mod common;
mod diagnostics_access;
mod durable_output_batch_tests;
mod frozen_surface;
mod input_staging_tests;
mod load_build_tick;
mod output_columns_tests;
mod outputs_lookup_tests;
mod params_tests;
mod projection_tests;
mod realtime_write_back_tests;
mod sim_tests;
mod state_codec_tests;
mod state_compatibility_tests;
mod state_continuation_tests;
mod state_family_tests;
mod state_format_golden_tests;
mod state_lifecycle_tests;
mod state_lowering_tests;
mod state_portability_tests;
mod state_resource_tests;
mod state_restore_validation_tests;
mod state_tests;
mod state_time_boundary_tests;
mod store_backed_inputs;
mod watch_tests;
